export const REQUEST = {
  NEW_REUQEST_DRAFT: "NEW_REQUEST_DRAFT",
  CLEAR_REQUEST_DRAFT: "CLEAR_REQUEST_DRAFT",
  GET_OPTIONS: "REQUEST_GET_OPTIONS",
  GET_PENDING: "REQUEST_GET_PENDING",
  GET_ALL: "REQUEST_GET_ALL",
};
export const SET_ACTIVE_STEP = "SET_ACTIVE_STEP";
export const SET_ACTIVE_PAGE = "SET_ACTIVE_PAGE";
export const LOGOUT = "LOGOUT";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";

export const LOADER = {
  SHOW: "SHOW_LOADER",
  HIDE: "HIDE_LOADER",
};

export const MESSAGE = {
  DISPLAY: "DISPLAY_MESSAGE",
  SUCCESS: "SUCCESS",
  ERROR: "ERROR",
  CLEAN_ERROR: "CLEAN_ERROR",
  WRONG_DATA: "WRONG_DATA",
  NETWORK_ERROR: "NETWORK_ERROR",
  WRONG_LOGIN_CREDENTIALS: "WRONG_LOGIN_CREDENTIALS",
  ACCESS_DENIED: "ACCESS_DENIED",
  SOMETHING_WENT_WRONG: "SOMETHING_WENT_WRONG",
};

export const SETTINGS = {
  TYPE: "SETTINGS_TYPE",
  SERVICES: "SETTINGS_SERVICE",
  ADD: "SETTINGS_ADD_SERVCIE",
  ADD_SERVICE_BASIC_DETAILS: "SETTINGS_ADD_SERVICE_BASIC_DETAILS",
  ADD_MORE_SERVICE: "SETTINGS_ADD_MORE_SERVICE",
  ADD_MORE_SERVICE_OPTIONS: "SETTINGS_ADD_MORE_SERVICE_OPTIONS",
  ADD_MORE_SERVICE_FIELDS: "SETTINGS_ADD_MORE_SERVICE_FIELDS",
  SUBMIT_SERVICE: "SETTINGS_SUBMIT_SERVICE",
};
